version: "3.8"

services:
  custom-gpt-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom_gpt_platform_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - ENV=production
      - DEBUG=false
    volumes:
      - ./app/models:/app/app/models:ro
    restart: unless-stopped
